development:
  adapter: postgresql
  encoding: unicode
  database: now_hiring_development
  pool: 5
  username: alankrumholz
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: now_hiring_test
  pool: 5
  username: alankrumholz
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: now_hiring_production
  pool: 5
  username: alankrumholz
  password: password